[package]
name = "cargo-snapper"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
cargo_metadata = "0.15.4"
clap = { version = "4.2.7", features = ["derive"] }
