[package]
name = "snapper"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
snapper-build = { version = "0.1", path = "../build", optional = true }

[features]
default = []
build = ["snapper-build"]
